Repository New-ReLINK/ReLINK, pull requests merged in 2024-12, with the labels that each got.

#41 FEAT: Spring Security 를 이용한 인증/인가 구현
  src/main/java/com/my/relink/config/SecurityConfig.java
  src/main/java/com/my/relink/config/security/AuthUser.java
  src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
  src/main/java/com/my/relink/config/security/LoginAuthentication.java
  src/main/java/com/my/relink/config/security/LoginAuthenticationFilter.java
  src/main/java/com/my/relink/config/security/LoginAuthenticationProvider.java
  src/main/java/com/my/relink/config/security/config/SecurityConfig.java
  src/main/java/com/my/relink/config/security/dto/req/LoginRepDto.java
  src/main/java/com/my/relink/config/security/dto/resp/LoginRespDto.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
  src/main/java/com/my/relink/domain/user/User.java
  src/main/java/com/my/relink/domain/user/UserRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/ex/SecurityFilterChainException.java
Labels: FEATURE

#40 FEAT: JWT Provider 구현
  build.gradle
  src/main/java/com/my/relink/config/SecurityConfig.java
  src/main/java/com/my/relink/config/security/AuthUser.java
  src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
  src/main/java/com/my/relink/config/security/LoginAuthentication.java
  src/main/java/com/my/relink/config/security/LoginAuthenticationFilter.java
  src/main/java/com/my/relink/config/security/LoginAuthenticationProvider.java
  src/main/java/com/my/relink/config/security/config/SecurityConfig.java
  src/main/java/com/my/relink/config/security/dto/req/LoginRepDto.java
  src/main/java/com/my/relink/config/security/dto/resp/LoginRespDto.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
  src/main/java/com/my/relink/domain/user/User.java
  src/main/java/com/my/relink/domain/user/UserRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/ex/SecurityFilterChainException.java
  src/main/java/com/my/relink/util/api/ApiError.java
  src/main/java/com/my/relink/util/api/ApiResult.java
  src/main/resources/application-dev.yaml
Labels: FEATURE

#45 FEAT: 사용자 정보 조회 페이지
  src/main/java/com/my/relink/config/security/AuthUser.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
  src/main/java/com/my/relink/controller/TradeController.java
  src/main/java/com/my/relink/controller/UserController.java
  src/main/java/com/my/relink/domain/image/Image.java
  src/main/java/com/my/relink/domain/image/ImageRepository.java
  src/main/java/com/my/relink/domain/point/Point.java
  src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
  src/main/java/com/my/relink/domain/point/repository/PointRepository.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/domain/trade/dto/TradeRequestDto.java
  src/main/java/com/my/relink/domain/trade/dto/TradeRequestResponseDto.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/dto/user/resp/UserInfoRespDto.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/java/com/my/relink/util/api/ApiError.java
  src/main/java/com/my/relink/util/api/ApiResult.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#44 FEAT: 회원가입 기능 구현
  src/main/java/com/my/relink/config/security/AuthUser.java
  src/main/java/com/my/relink/config/security/dto/req/LoginRepDto.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
  src/main/java/com/my/relink/controller/TradeController.java
  src/main/java/com/my/relink/controller/UserController.java
  src/main/java/com/my/relink/domain/image/Image.java
  src/main/java/com/my/relink/domain/image/ImageRepository.java
  src/main/java/com/my/relink/domain/point/Point.java
  src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
  src/main/java/com/my/relink/domain/point/repository/PointRepository.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/domain/trade/dto/TradeRequestDto.java
  src/main/java/com/my/relink/domain/trade/dto/TradeRequestResponseDto.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/domain/user/Address.java
  src/main/java/com/my/relink/dto/user/req/AddressCreateReqDto.java
  src/main/java/com/my/relink/dto/user/req/UserCreateReqDto.java
  src/main/java/com/my/relink/dto/user/resp/UserCreateRespDto.java
  src/main/java/com/my/relink/dto/user/resp/UserInfoRespDto.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/java/com/my/relink/util/api/ApiError.java
  src/main/java/com/my/relink/util/api/ApiResult.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#60 REFACTOR: 토큰에 ID 값 추가
  src/main/java/com/my/relink/config/security/AuthUser.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
Labels: REFACTOR

#63 FIX: BaseEntity 오류 해결
  src/main/java/com/my/relink/domain/BaseEntity.java
Labels: FIX

#65 Feat: 문의하기 버튼 클릭 시 거래 상세 정보 조회하기
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/response/ExchangeItemInfoDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeInquiryDetailRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradePartnerInfoDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeStatusInfoDto.java
  src/main/java/com/my/relink/domain/image/ImageRepository.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/review/Review.java
  src/main/java/com/my/relink/domain/review/ReviewRepository.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/java/com/my/relink/service/UserTrustScoreService.java
  src/main/java/com/my/relink/util/DummyObject.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
  src/test/java/com/my/relink/service/UserServiceTest.java
  src/test/java/com/my/relink/service/UserTrustScoreServiceTest.java
Labels: FEATURE

#59 Feat : 교환 신청 취소
  .gitignore
  src/main/java/com/my/relink/ReLinkApplication.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeRequestRespDto.java
  src/main/java/com/my/relink/domain/point/Point.java
  src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
  src/main/java/com/my/relink/domain/trade/dto/TradeRequestDto.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/PointTransactionService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/util/api/ApiResult.java
  src/main/resources/application-dev.yaml
Labels: FEATURE

#64 Feature : 내 교환상품 등록
  src/main/java/com/my/relink/common/validation/EnumValidator.java
  src/main/java/com/my/relink/common/validation/EnumValidatorImpl.java
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/CreateExchangeItemReqDto.java
  src/main/java/com/my/relink/domain/category/Category.java
  src/main/java/com/my/relink/domain/category/repository/CategoryRepository.java
  src/main/java/com/my/relink/domain/item/ItemStatus.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/point/Point.java
  src/main/java/com/my/relink/domain/user/User.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/test/java/com/my/relink/ExchangeItem/ExchangeItemServiceTest.java
Labels: FEATURE

#67 FEAT: 이메일 중복 검사 기능 구현
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/controller/user/dto/req/UserValidEmailReqDto.java
  src/main/java/com/my/relink/controller/user/dto/resp/UserValidEmailRespDto.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#70 FEAT: 회원 탈퇴 기능 구현
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/controller/user/dto/req/UserDeleteReqDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/user/User.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/resources/application-dev.yml
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#71 FEAT: 회원 정보 수정 기능 구현
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/controller/user/dto/req/UserInfoEditReqDto.java
  src/main/java/com/my/relink/domain/user/User.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#73 FIX: JWT 타입 캐스팅 에러 해결
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
Labels: FIX

#74 FEAT: 사용자 주소 조회 기능 구현
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/controller/user/dto/resp/UserAddressRespDto.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#66 Feat : 기부 상품 등록
  src/main/java/com/my/relink/controller/item/donation/DonationController.java
  src/main/java/com/my/relink/controller/item/donation/dto/DonationItemReqDto.java
  src/main/java/com/my/relink/controller/item/donation/dto/DonationItemRespDto.java
  src/main/java/com/my/relink/controller/item/donation/repository/DonationItemRepository.java
  src/main/java/com/my/relink/controller/item/donation/validation/ItemQualityValidator.java
  src/main/java/com/my/relink/controller/item/donation/validation/ValidItemQuality.java
  src/main/java/com/my/relink/domain/item/donation/DonationItem.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItemRepository.java
  src/main/java/com/my/relink/service/DonationItemService.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#82 FEAT: 내 관심 상품 목록 조회 기능 구현
  src/main/java/com/my/relink/controller/like/LikeController.java
  src/main/java/com/my/relink/controller/like/dto/resp/LikeExchangeItemListRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/like/Like.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepository.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
  src/main/java/com/my/relink/domain/like/repository/dto/LikeExchangeItemListRepositoryDto.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/service/LikeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/java/com/my/relink/util/page/PageInfo.java
  src/main/java/com/my/relink/util/page/PageResponse.java
  src/test/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImplTest.java
Labels: FEATURE

#78 FEAT: 사용자가 작성한 후기 단건 조회 기능 구현
  build.gradle
  src/main/java/com/my/relink/config/QueryDsl/QuerydslConfig.java
  src/main/java/com/my/relink/controller/exchange/dto/resp/ExchangeItemImageListRespDto.java
  src/main/java/com/my/relink/controller/like/LikeController.java
  src/main/java/com/my/relink/controller/like/dto/resp/LikeExchangeItemListRespDto.java
  src/main/java/com/my/relink/controller/review/ReviewController.java
  src/main/java/com/my/relink/controller/review/dto/resp/ReviewDetailsRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/like/Like.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepository.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
  src/main/java/com/my/relink/domain/like/repository/dto/LikeExchangeItemListRepositoryDto.java
  src/main/java/com/my/relink/domain/review/Review.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepository.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/my/relink/domain/review/repository/ReviewRepository.java
  src/main/java/com/my/relink/domain/review/repository/dto/ReviewDetailRepositoryDto.java
  src/main/java/com/my/relink/domain/review/repository/dto/ReviewDetailWithOutTradeReview.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/LikeService.java
  src/main/java/com/my/relink/service/ReviewService.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/java/com/my/relink/service/UserTrustScoreService.java
  src/main/java/com/my/relink/util/DateTimeFormatterUtil.java
  src/main/java/com/my/relink/util/page/PageInfo.java
  src/main/java/com/my/relink/util/page/PageResponse.java
  src/test/java/com/my/relink/config/TestConfig.java
  src/test/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImplTest.java
  src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/com/my/relink/service/UserTrustScoreServiceTest.java
Labels: FEATURE

#94 FEAT: 사용자가 작성한 후기 내역 페이지 조회 기능 구현
  src/main/java/com/my/relink/controller/review/ReviewController.java
  src/main/java/com/my/relink/controller/review/dto/resp/ReviewListRespDto.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepository.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/my/relink/domain/review/repository/dto/ReviewListRepositoryDto.java
  src/main/java/com/my/relink/domain/review/repository/dto/ReviewListWithOutTradeStatusRepositoryDto.java
  src/main/java/com/my/relink/service/ReviewService.java
  src/test/java/com/my/relink/ExchangeItem/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryTest.java
Labels: FEATURE

#98 FEAT: 사용자 정보 조회 페이지 구현
  src/main/java/com/my/relink/ReLinkApplication.java
  src/main/java/com/my/relink/controller/item/donation/dto/DonationItemReqDto.java
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/controller/user/dto/resp/UserProfileRespDto.java
  src/main/java/com/my/relink/domain/item/donation/DonationItem.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/my/relink/domain/review/repository/ReviewRepository.java
  src/main/java/com/my/relink/domain/user/repository/CustomUserRepository.java
  src/main/java/com/my/relink/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/com/my/relink/domain/user/repository/UserRepository.java
  src/main/java/com/my/relink/domain/user/repository/dto/UserInfoWithCountRepositoryDto.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/java/com/my/relink/service/UserTrustScoreService.java
  src/test/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImplTest.java
  src/test/java/com/my/relink/domain/user/repository/CustomUserRepositoryImplTest.java
  src/test/java/com/my/relink/service/UserTrustScoreServiceTest.java
Labels: FEATURE

#111 FEAT: 사용자 신뢰도 페이지 (신뢰도 정보만)
  src/main/java/com/my/relink/controller/review/ReviewController.java
  src/main/java/com/my/relink/controller/review/dto/resp/ReviewStatisticsRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/review/repository/ReviewRepository.java
  src/main/java/com/my/relink/service/ReviewService.java
Labels: FEATURE

#112 FEAT: 사용자 신뢰도 페이지(후기 목록들만)
  src/main/java/com/my/relink/controller/review/ReviewController.java
  src/main/java/com/my/relink/controller/review/dto/resp/ReviewWithExchangeItemListRespDto.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepository.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/my/relink/domain/review/repository/dto/ReviewWithExchangeItemRepositoryDto.java
  src/main/java/com/my/relink/service/ReviewService.java
  src/test/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImplTest.java
  src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImplTest.java
Labels: FEATURE

#87 Feat : 내 교환 상품 목록 보기
  src/main/java/com/my/relink/common/validation/EnumValidatorImpl.java
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/req/CreateExchangeItemReqDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemRespDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemsByUserRespDto.java
  src/main/java/com/my/relink/domain/BaseEntity.java
  src/main/java/com/my/relink/domain/image/repository/CumtomImageRepositoryImpl.java
  src/main/java/com/my/relink/domain/image/repository/CustomImageRepository.java
  src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepository.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepositoryImpl.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImplTest.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#115 FEAT: 거래 신고 페이지 조회
  src/main/java/com/my/relink/controller/report/ReportController.java
  src/main/java/com/my/relink/controller/report/dto/response/TradeInfoRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/domain/user/User.java
  src/main/java/com/my/relink/domain/user/repository/CustomUserRepository.java
  src/main/java/com/my/relink/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/com/my/relink/domain/user/repository/UserRepository.java
  src/main/java/com/my/relink/service/ReportService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/util/DateTimeUtil.java
  src/test/java/com/my/relink/service/ReportServiceTest.java
Labels: FEATURE

#120 FEAT: 교환 상품 신고 페이지 조회
  src/main/java/com/my/relink/controller/report/ReportController.java
  src/main/java/com/my/relink/controller/report/dto/response/ExchangeItemInfoRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/ReportService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/service/ReportServiceTest.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#122 FEAT: 알림 발행 기능
  src/main/java/com/my/relink/ReLinkApplication.java
  src/main/java/com/my/relink/common/notification/NotificationEvent.java
  src/main/java/com/my/relink/common/notification/NotificationEventListener.java
  src/main/java/com/my/relink/common/notification/NotificationPublisherService.java
  src/main/java/com/my/relink/common/notification/NotificationType.java
  src/main/java/com/my/relink/controller/notification/NotificationController.java
  src/main/java/com/my/relink/domain/notification/Notification.java
  src/main/java/com/my/relink/domain/notification/chat/ChatNotification.java
  src/main/java/com/my/relink/domain/notification/chat/repository/ChatNotificationRepository.java
  src/main/java/com/my/relink/domain/notification/donation/DonationNotification.java
  src/main/java/com/my/relink/domain/notification/donation/repository/DonationNotificationRepository.java
  src/main/java/com/my/relink/domain/notification/exchange/ExchangeNotification.java
  src/main/java/com/my/relink/domain/notification/exchange/repository/ExchangeNotificationRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
Labels: FEATURE

#133 FEAT: Env 설정 추가
  .env
  .gitignore
  build.gradle
  src/main/resources/application-dev.yaml
Labels: FEATURE

#100 Feat: 교환 진행 페이지 조회
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeCompletionRespDto.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/util/DateTimeUtil.java
  src/main/java/com/my/relink/util/DummyObject.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#134 Feat : 내 기부 내역 조회
  src/main/java/com/my/relink/controller/donation/DonationController.java
  src/main/java/com/my/relink/controller/donation/dto/req/DonationItemReqDto.java
  src/main/java/com/my/relink/controller/donation/dto/resp/DonationCompleteItemUserRespDto.java
  src/main/java/com/my/relink/controller/donation/dto/resp/DonationItemUserListRespDto.java
  src/main/java/com/my/relink/controller/donation/dto/resp/DonationItemUserRespDto.java
  src/main/java/com/my/relink/domain/item/donation/DonationItem.java
  src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
  src/main/java/com/my/relink/service/DonationItemService.java
Labels: FEATURE

#110 Feat : 교환 취소하기 페이지 조회
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeCancelRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeCompletionRespDto.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#119 Feat : 교환 취소하기
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/request/TradeCancelReqDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeCancelRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/ViewTradeCancelRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/PointTransactionService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/util/DummyObject.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#135 Feat : 내 교환 상품을 수정하기 위해 진입하는 페이지
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemRespDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemsRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: FEATURE

#141 Feat : 리뷰 페이지 조회
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/response/ViewReviewRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/ViewTradeCancelRespDto.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#149 FEAT: 토스페이먼츠 결제 위젯 테스트를 위한 화면 구현
  build.gradle
  src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
  src/main/java/com/my/relink/config/security/config/SecurityConfig.java
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemRespDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemsRespDto.java
  src/main/java/com/my/relink/controller/payment/PaymentController.java
  src/main/java/com/my/relink/controller/payment/PaymentViewController.java
  src/main/java/com/my/relink/controller/trade/TradeController.java
  src/main/java/com/my/relink/controller/trade/dto/request/TradeCancelReqDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeCancelRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeCompletionRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/ViewReviewRespDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/ViewTradeCancelRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepository.java
  src/main/java/com/my/relink/domain/trade/Trade.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/PointTransactionService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/util/DummyObject.java
  src/main/resources/templates/charge/charge-fail.html
  src/main/resources/templates/charge/charge-form.html
  src/main/resources/templates/charge/charge-success.html
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#142 FEAT: 토스페이먼츠 통신을 위한 RestClient 기반 결제 클라이언트 구현
  build.gradle
  src/main/java/com/my/relink/client/tosspayments/TossPaymentApiPath.java
  src/main/java/com/my/relink/client/tosspayments/TossPaymentClient.java
  src/main/java/com/my/relink/client/tosspayments/config/RestClientConfig.java
  src/main/java/com/my/relink/client/tosspayments/dto/request/TossPaymentCancelReqDto.java
  src/main/java/com/my/relink/client/tosspayments/dto/request/TossPaymentReqDto.java
  src/main/java/com/my/relink/client/tosspayments/dto/response/TossPaymentErrorRespDto.java
  src/main/java/com/my/relink/client/tosspayments/dto/response/TossPaymentRespDto.java
  src/main/java/com/my/relink/client/tosspayments/ex/PaymentFeature.java
  src/main/java/com/my/relink/client/tosspayments/ex/TossPaymentErrorCode.java
  src/main/java/com/my/relink/client/tosspayments/ex/TossPaymentException.java
  src/main/java/com/my/relink/client/tosspayments/ex/TossPaymentNetworkException.java
  src/main/java/com/my/relink/client/tosspayments/ex/badRequest/TossPaymentBadRequestException.java
  src/main/java/com/my/relink/client/tosspayments/ex/forbidden/TossPaymentForbiddenException.java
  src/main/java/com/my/relink/client/tosspayments/ex/notFound/TossPaymentNotFoundException.java
  src/main/java/com/my/relink/client/tosspayments/ex/serverError/TossPaymentServerException.java
  src/main/java/com/my/relink/client/tosspayments/ex/unAuthorized/TossPaymentUnauthorizedException.java
  src/main/java/com/my/relink/config/RetryConfig.java
  src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
  src/main/java/com/my/relink/config/security/config/SecurityConfig.java
  src/main/java/com/my/relink/controller/payment/PaymentController.java
  src/main/java/com/my/relink/controller/payment/PaymentViewController.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/resources/application-dev.yaml
  src/main/resources/templates/charge/charge-fail.html
  src/main/resources/templates/charge/charge-form.html
  src/main/resources/templates/charge/charge-success.html
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#156 Feat : 내 교환 상품 수정
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/req/UpdateExchangeItemReqDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: FEATURE

#159 Feat : 교환 상품 찜/해제 하기
  src/main/java/com/my/relink/controller/like/LikeController.java
  src/main/java/com/my/relink/domain/like/Like.java
  src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
  src/main/java/com/my/relink/service/LikeService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/service/LikeServiceTest.java
Labels: FEATURE

#143 FEAT: S3 Config 추가
  build.gradle
  src/main/java/com/my/relink/config/s3/S3Config.java
  src/main/java/com/my/relink/config/s3/S3Service.java
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/UserService.java
  src/main/resources/application-dev.yaml
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#144 FEAT: 사용자 프로필 사진 등록 기능
  src/main/java/com/my/relink/controller/image/ImageController.java
  src/main/java/com/my/relink/controller/image/dto/resp/ImageUserProfileCreateRespDto.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ImageService.java
  src/test/java/com/my/relink/service/ImageServiceTest.java
Labels: FEATURE

#145 FEAT: 사용자 프로필 사진 삭제 기능
  src/main/java/com/my/relink/controller/image/ImageController.java
  src/main/java/com/my/relink/controller/image/dto/resp/ImageUserProfileDeleteRespDto.java
  src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ImageService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/service/ImageServiceTest.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE

#146 FIX: 회원 탈퇴 시 교환 가능 상품을 교환 불가로 변경
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/controller/message/MessageControllerTest.java
  src/test/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepositoryTest.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: FEATURE, FIX

#162 Feat : 내 교환 상품 삭제
  src/main/java/com/my/relink/chat/service/ChatService.java
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
  src/main/java/com/my/relink/domain/message/repository/MessageRepository.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/LikeService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: FEATURE

#166 Refactor : 순환참조 발생 관련 코드 수정
  src/main/java/com/my/relink/service/LikeService.java
Labels: REFACTOR

#160 Feat: 포인트 충전을 위한 결제 서비스 구현
  src/main/java/com/my/relink/client/tosspayments/TossPaymentClient.java
  src/main/java/com/my/relink/client/tosspayments/dto/request/TossPaymentReqDto.java
  src/main/java/com/my/relink/client/tosspayments/dto/response/TossPaymentRespDto.java
  src/main/java/com/my/relink/client/tosspayments/feature/PaymentFeature.java
  src/main/java/com/my/relink/client/tosspayments/feature/PaymentStatus.java
  src/main/java/com/my/relink/controller/payment/PaymentController.java
  src/main/java/com/my/relink/controller/payment/dto/request/PaymentReqDto.java
  src/main/java/com/my/relink/controller/payment/dto/response/PaymentRespDto.java
  src/main/java/com/my/relink/domain/payment/Payment.java
  src/main/java/com/my/relink/domain/payment/PaymentCancelReason.java
  src/main/java/com/my/relink/domain/payment/PaymentType.java
  src/main/java/com/my/relink/domain/payment/repository/PaymentRepository.java
  src/main/java/com/my/relink/domain/point/Point.java
  src/main/java/com/my/relink/domain/point/pointHistory/PointHistory.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/PointService.java
  src/main/java/com/my/relink/service/payment/PaymentService.java
  src/main/java/com/my/relink/service/payment/PaymentServiceFacade.java
  src/main/java/com/my/relink/service/payment/dto/PaymentValidation.java
  src/main/java/com/my/relink/service/payment/ex/PaymentCancelFailException.java
  src/main/resources/templates/charge/charge-success.html
  src/test/java/com/my/relink/service/payment/PaymentServiceTest.java
Labels: FEATURE

#169 FEAT: 결제 프로세스
  .env
  .gitignore
  src/main/java/com/my/relink/ReLinkApplication.java
  src/main/java/com/my/relink/client/tosspayments/TossPaymentClient.java
  src/main/java/com/my/relink/client/tosspayments/dto/response/TossPaymentRespDto.java
  src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
  src/main/java/com/my/relink/config/security/config/SecurityConfig.java
  src/main/java/com/my/relink/controller/payment/PaymentController.java
  src/main/java/com/my/relink/controller/payment/dto/request/PaymentReqDto.java
  src/main/java/com/my/relink/controller/payment/dto/response/PaymentRespDto.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/handler/GlobalExceptionHandler.java
  src/main/java/com/my/relink/service/payment/PaymentProcessService.java
  src/main/java/com/my/relink/service/payment/PaymentService.java
  src/main/java/com/my/relink/service/payment/PaymentServiceFacade.java
  src/main/java/com/my/relink/util/api/ApiResult.java
  src/main/resources/templates/charge/charge-form.html
  src/main/resources/templates/charge/charge-success.html
  src/test/java/com/my/relink/service/payment/PaymentProcessServiceTest.java
  src/test/java/com/my/relink/service/payment/PaymentServiceTest.java
Labels: FEATURE

#151 FEAT: 전역 필터 예외 처리 필터 구현
  .gitignore
  src/main/java/com/my/relink/ReLinkApplication.java
  src/main/java/com/my/relink/config/security/GlobalFilterExceptionHandler.java
  src/main/java/com/my/relink/config/security/config/SecurityConfig.java
  src/main/java/com/my/relink/config/security/jwt/JwtProvider.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#150 Feat : 리뷰 작성하기
  src/main/java/com/my/relink/controller/review/ReviewController.java
  src/main/java/com/my/relink/controller/review/dto/request/ReviewReqDto.java
  src/main/java/com/my/relink/controller/review/dto/resp/ReviewRespDto.java
  src/main/java/com/my/relink/domain/review/repository/ReviewRepository.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ReviewService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/util/DummyObject.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#153 FIX: 탈퇴한 사용자 로그인 불가 처리
  src/main/java/com/my/relink/config/security/LoginAuthenticationProvider.java
  src/main/java/com/my/relink/domain/user/repository/UserRepository.java
  src/test/java/com/my/relink/config/TestConfig.java
  src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/com/my/relink/service/LikeServiceTest.java
Labels: FIX

#168 Feat : 전체 사용자가 보는 교환 상품 목록 조회
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/req/GetAllExchangeItemReqDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetAllExchangeItemsRespDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemRespDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemsRespDto.java
  src/main/java/com/my/relink/domain/image/repository/CustomImageRepository.java
  src/main/java/com/my/relink/domain/image/repository/CustomImageRepositoryImpl.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepository.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/util/page/PageInfo.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: FEATURE

#172 Feat : 기부 알림 자세한 화면: 기부 완료 (조회)
  src/main/java/com/my/relink/controller/donation/DonationController.java
  src/main/java/com/my/relink/controller/donation/dto/resp/DonationCompleteItemDetailRespDto.java
  src/main/java/com/my/relink/domain/image/EntityType.java
  src/main/java/com/my/relink/service/DonationItemService.java
  src/main/java/com/my/relink/service/ImageService.java
Labels: FEATURE

#183 FEAT: 채팅 이미지 저장 & 채팅 시 알림 발행 로직 추가
  src/main/java/com/my/relink/chat/controller/ChatController.java
  src/main/java/com/my/relink/chat/controller/dto/request/ChatImageReqDto.java
  src/main/java/com/my/relink/chat/controller/dto/request/ChatMessageReqDto.java
  src/main/java/com/my/relink/chat/controller/dto/response/ChatImageRespDto.java
  src/main/java/com/my/relink/chat/controller/dto/response/ChatMessageRespDto.java
  src/main/java/com/my/relink/chat/service/ChatService.java
  src/main/java/com/my/relink/domain/image/EntityType.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/chat/service/ChatServiceTest.java
Labels: FEATURE, REFACTOR

#174 FEAT: 포인트 충전 내역 페이지 조회
  src/main/java/com/my/relink/controller/point/PointController.java
  src/main/java/com/my/relink/controller/point/dto/response/PointChargeHistoryRespDto.java
  src/main/java/com/my/relink/domain/payment/repository/PaymentCustomRepository.java
  src/main/java/com/my/relink/domain/payment/repository/PaymentCustomRepositoryImpl.java
  src/main/java/com/my/relink/domain/payment/repository/PaymentRepository.java
  src/main/java/com/my/relink/domain/payment/repository/dto/PointChargeHistoryDto.java
  src/main/java/com/my/relink/service/payment/PaymentService.java
  src/test/java/com/my/relink/service/payment/PaymentServiceTest.java
Labels: FEATURE

#167 Refactor : 유저가 탈퇴했을 때 거래 시나리오
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/main/java/com/my/relink/domain/user/repository/UserRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ReviewService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: REFACTOR

#177 REFACTOR: 포인트 사용 내역 조회 리팩토링
  src/main/java/com/my/relink/controller/point/dto/response/PointUsageHistoryRespDto.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryCustomRepository.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryCustomRepositoryImpl.java
  src/main/java/com/my/relink/domain/point/pointHistory/repository/dto/PointUsageHistoryDto.java
  src/main/java/com/my/relink/service/PointHistoryService.java
  src/test/java/com/my/relink/domain/point/pointHistory/repository/PointHistoryRepositoryTest.java
  src/test/java/com/my/relink/service/PointHistoryServiceTest.java
Labels: REFACTOR

#184 Feat : 거래 관련 알림 발행
  src/main/java/com/my/relink/service/TradeService.java
Labels: FEATURE

#173 Feat : 기부 상품 삭제하기
  src/main/java/com/my/relink/controller/donation/DonationController.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/DonationItemService.java
Labels: FEATURE

#163 Feat: 기부 알림 자세한 화면 : 검수 부적합
  src/main/java/com/my/relink/controller/donation/DonationController.java
  src/main/java/com/my/relink/controller/donation/dto/resp/DonationItemRejectionRespDto.java
  src/main/java/com/my/relink/domain/item/donation/DonationStatus.java
  src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
  src/main/java/com/my/relink/service/DonationItemService.java
  src/main/java/com/my/relink/service/ImageService.java
Labels: FEATURE

#188 FEAT: 웹소켓 연결 시 jwt 예외 처리 추가하기
  src/main/java/com/my/relink/chat/handler/StompHandler.java
  src/test/java/com/my/relink/chat/handler/StompHandlerTest.java
Labels: FEATURE, REFACTOR

#192 Feat : 교환할 내 물품 선택 페이지(조회)
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/GetExchangeItemRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepository.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: FEATURE

#189 Refactor: tradeRepository에 QueryDsl 적용
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepository.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepositoryImpl.java
  src/main/java/com/my/relink/domain/trade/repository/TradeRepository.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: REFACTOR

#193 Feat : 교환할 내 물품 선택
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/req/ChoiceExchangeItemReqDto.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/req/GetAllExchangeItemReqDto.java
  src/main/java/com/my/relink/controller/trade/dto/response/TradeIdRespDto.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepositoryTest.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/service/TradeServiceTest.java
Labels: FEATURE

#197 Feat : 기부 상품 사진등록
  src/main/java/com/my/relink/controller/image/ImageController.java
  src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
  src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ImageService.java
Labels: FEATURE

#198 TEST: 테스트 케이스 수정
  src/test/java/com/my/relink/service/TradeServiceTest.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: TEST

#200 BUILD: 빌드 방식 선택 기능 추가
  build.gradle
  src/main/java/com/my/relink/ReLinkApplication.java
Labels: FEATURE

#202 Refactor : 교환할 내 물품 선택 오타 및 코드 수정
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: REFACTOR

#204 Feat : 기부 상품 사진 삭제
  src/main/java/com/my/relink/controller/image/ImageController.java
  src/main/java/com/my/relink/service/ImageService.java
Labels: FEATURE

#187 FEAT: 거래 신고 이미지 저장
  src/main/java/com/my/relink/chat/controller/dto/request/ChatImageReqDto.java
  src/main/java/com/my/relink/common/validation/ValidFile.java
  src/main/java/com/my/relink/common/validation/ValidFileValidator.java
  src/main/java/com/my/relink/controller/report/ReportController.java
  src/main/java/com/my/relink/controller/report/dto/request/UploadImagesForReportReqDto.java
  src/main/java/com/my/relink/controller/report/dto/response/UploadImagesForReportRespDto.java
  src/main/java/com/my/relink/domain/report/repository/ReportRepository.java
  src/main/java/com/my/relink/ex/ErrorCode.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/ReportService.java
  src/test/java/com/my/relink/service/ReportServiceTest.java
Labels: FEATURE

#218 Refactor : QueryDSL 변경작업
  src/main/java/com/my/relink/chat/service/ChatService.java
  src/main/java/com/my/relink/domain/image/repository/CustomImageRepository.java
  src/main/java/com/my/relink/domain/image/repository/CustomImageRepositoryImpl.java
  src/main/java/com/my/relink/domain/image/repository/ImageRepository.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepository.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
  src/main/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepository.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepository.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/my/relink/domain/like/repository/LikeRepository.java
  src/main/java/com/my/relink/domain/message/repository/CustomMessageRepository.java
  src/main/java/com/my/relink/domain/message/repository/CustomMessageRepositoryImpl.java
  src/main/java/com/my/relink/domain/message/repository/MessageRepository.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/LikeService.java
  src/main/java/com/my/relink/service/UserService.java
  src/test/java/com/my/relink/domain/item/exchange/repository/ExchangeItemRepositoryTest.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
  src/test/java/com/my/relink/service/ImageServiceTest.java
  src/test/java/com/my/relink/service/LikeServiceTest.java
  src/test/java/com/my/relink/service/UserServiceTest.java
Labels: REFACTOR

#206 FEAT: Github Action CI 파일 추가
  .github/workflows/pr-trigger.yml
  build.gradle
Labels: FEATURE

#220 Refactor : 기부 관련 QueryDSL로 변경
  src/main/java/com/my/relink/controller/donation/DonationController.java
  src/main/java/com/my/relink/controller/donation/dto/resp/DonationItemDetailRespDto.java
  src/main/java/com/my/relink/domain/item/donation/repository/CustomDonationItemRepository.java
  src/main/java/com/my/relink/domain/item/donation/repository/CustomDonationItemRepositoryImpl.java
  src/main/java/com/my/relink/domain/item/donation/repository/DonationItemRepository.java
  src/main/java/com/my/relink/service/DonationItemService.java
  src/main/java/com/my/relink/service/ImageService.java
Labels: REFACTOR

#221 Refactor : 교환 상품 삭제 시 거래 삭제
  src/main/java/com/my/relink/chat/service/ChatService.java
  src/main/java/com/my/relink/domain/image/repository/CustomImageRepositoryImpl.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
  src/main/java/com/my/relink/domain/like/repository/CustomLikeRepositoryImpl.java
  src/main/java/com/my/relink/domain/message/repository/CustomMessageRepositoryImpl.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepository.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepositoryImpl.java
  src/main/java/com/my/relink/service/DonationItemService.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ImageService.java
  src/main/java/com/my/relink/service/LikeService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/test/java/com/my/relink/service/ExchangeItemServiceTest.java
Labels: REFACTOR
