Repository New-ReLINK/ReLINK, pull requests merged in 2025-01, with the labels that each got.

#225 Feat : 기부 관련 알림 발행
  src/main/java/com/my/relink/service/DonationItemService.java
Labels: FEATURE

#228 [REFACTOR] : QueryDsl 성능 개선
  src/main/java/com/my/relink/common/notification/NotificationPublisherService.java
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
  src/main/java/com/my/relink/controller/exchangeItem/dto/resp/FindAllExchangeItemListRespDto.java
  src/main/java/com/my/relink/controller/user/UserController.java
  src/main/java/com/my/relink/domain/item/exchange/ExchangeItem.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepository.java
  src/main/java/com/my/relink/domain/item/exchange/repository/CustomExchangeItemRepositoryImpl.java
  src/main/java/com/my/relink/domain/item/exchange/repository/dto/FindExchangeItemListRepositoryDto.java
  src/main/java/com/my/relink/domain/review/Review.java
  src/main/java/com/my/relink/domain/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/com/my/relink/service/ExchangeItemService.java
  src/main/java/com/my/relink/service/ReviewService.java
  src/test/java/com/my/relink/domain/review/repository/CustomReviewRepositoryTest.java
Labels: FEATURE

#230 [DOCS] : README 작성
  README.md
  images/ERD.png
  images/euijeon.png
  images/gunwoo.png
  images/hanbi.png
  images/project_img.png
  images/siyeon.png
  images/system_architecture.png
  images/yewoon.png
Labels: DOCS

#232 REFACTOR: 채팅 성능 개선
  .gitignore
  build.gradle
  src/main/java/com/my/relink/chat/aop/TradeCacheEvictionAspect.java
  src/main/java/com/my/relink/chat/aop/metric/OperationMetrics.java
  src/main/java/com/my/relink/chat/aop/metric/OperationMetricsAspect.java
  src/main/java/com/my/relink/chat/aop/metric/TimeMetric.java
  src/main/java/com/my/relink/chat/config/WebSocketConfig.java
  src/main/java/com/my/relink/chat/config/WebSocketMetricsCollector.java
  src/main/java/com/my/relink/chat/config/WebSocketSessionManager.java
  src/main/java/com/my/relink/chat/config/metric/TaskMetric.java
  src/main/java/com/my/relink/chat/config/metric/WebSocketMetricsHolder.java
  src/main/java/com/my/relink/chat/controller/dto/request/ChatMessageReqDto.java
  src/main/java/com/my/relink/chat/controller/dto/response/ChatMessageRespDto.java
  src/main/java/com/my/relink/chat/handler/StompHandler.java
  src/main/java/com/my/relink/chat/handler/metric/OperationMetrics.java
  src/main/java/com/my/relink/chat/service/ChatService.java
  src/main/java/com/my/relink/chat/service/cache/ChatCacheService.java
  src/main/java/com/my/relink/chat/service/cache/ChatMessage.java
  src/main/java/com/my/relink/chat/service/cache/metric/KeyMetadata.java
  src/main/java/com/my/relink/chat/service/cache/metric/RedisPerformanceMetrics.java
  src/main/java/com/my/relink/config/cache/CacheConfig.java
  src/main/java/com/my/relink/config/cache/RedisConfig.java
  src/main/java/com/my/relink/config/security/JwtAuthorizationFilter.java
  src/main/java/com/my/relink/config/time/TimeConfig.java
  src/main/java/com/my/relink/domain/message/Message.java
  src/main/java/com/my/relink/domain/message/repository/MessageRepository.java
  src/main/java/com/my/relink/domain/trade/TradeStatus.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepository.java
  src/main/java/com/my/relink/domain/trade/repository/CustomTradeRepositoryImpl.java
  src/main/java/com/my/relink/domain/trade/repository/dto/TradeWithOwnerItemNameDto.java
  src/main/java/com/my/relink/service/MessageService.java
  src/main/java/com/my/relink/service/TradeService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-test.yaml
  src/main/resources/logback-spring.xml
  src/main/resources/templates/charge/charge-success.html
  src/test/java/com/my/relink/chat/service/ChatSavePerformanceLocalTest.java
  src/test/java/com/my/relink/chat/service/ChatServiceTest.java
  src/test/java/com/my/relink/service/MessageServiceTest.java
Labels: REFACTOR

#235 REFACTOR: dev profile 로깅 레벨 조정
  src/main/resources/logback-spring.xml
Labels: REFACTOR

#243 Refactor : GET 사용시 RequestBody 제거 관련 수정
  src/main/java/com/my/relink/controller/exchangeItem/ExchangeItemController.java
Labels: REFACTOR
